spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-quiet-salad-ac3it7xy-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_0ZIl8JtFoDCW}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  jackson:
    default-property-inclusion: NON_NULL

github:
  oauth:
    client-id: ${GITHUB_CLIENT_ID:Ov23li05V5giSd6gdMiE}
    client-secret: ${GITHUB_CLIENT_SECRET:914135f2759808d961412c1c938718f026b4e48a}
    redirect-uri: ${BACKEND_URL:https://starboard-be.onrender.com}/api/auth/github/callback
    scope: user:email,repo

jwt:
  secret: ${JWT_SECRET:starboard_jwt_super_secret_key_minimum_256_bits_long_secure_key_2024}
  expiration: 86400000  # 24 hours

frontend:
  url: ${FRONTEND_URL:https://buff-startgit.vercel.app}

server:
  port: ${PORT:8080}

logging:
  level:
    com.starboard: DEBUG
    org.springframework.security: INFO

# Star verification job
star:
  verify:
    cron: "*/5 * * * * *"
